### ISSUE TITLE
Add Vehicles to Site-Wide Search

### ISSUE THREAD

**Issue by jren207** [jclgoodwin/bustimes.org#100]
Would be handy to be able to search for a vehicle using the site-wide search box.

Currently the only way to search for a vehicle is via search engines using a site search query, or finding the operator fleet list and CTRL+F your way through it.

**Comment by jclgoodwin** [comment]
Good idea, thanks. You can now (finally) search by reg or (5+ digit) number:
https://bustimes.org/search?q=bb70bus
https://bustimes.org/search?q=11111
