### ISSUE TITLE
Some Diamond vehicles also track as First Norfolk & Suffolk vehicles

### ISSUE THREAD

**Issue by djbusphotos** [jclgoodwin/bustimes.org#121]
I'm not sure if it's an issue with the site itself, or something on Diamond's end. If it's the latter, I can speak with my contacts there and get it sorted.

![image](https://user-images.githubusercontent.com/70415342/114259588-eafdad80-99c6-11eb-80a7-3eeed664403b.png)
Diamond 30961, tracking at Tividale Depot, before entering service on the 4H.

![image](https://user-images.githubusercontent.com/70415342/114259596-fbae2380-99c6-11eb-8a9c-d6ba9ade92a0.png)
First 30961, also tracking at Tividale Depot as a 4H, in roughly the same location as the Diamond one.

I'm no expert by any means, but it looks like the data being provided to BODS is being interpreted as both vehicles. It also seems to happen with other vehicles in the Diamond fleet, where there is another vehicle in the First Norfolk & Suffolk fleet with the same fleet number.

**Comment by jclgoodwin** [comment]
Fixed, thanks – was a problem with (my handling of) the Transport for West Midlands feed, which isn't really needed now that BODS exists.
