### ISSUE TITLE
Registration changes showing up under 'cancelled' table

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#130]
On the Hulleys registrations/vosa page, anything which they have registered upcoming, shows up under the cancelled registrations table despite there being no cancelled entries to the registration. 

https://bustimes.org/licences/PC0003407

This is happening on other operators. Seems to be anything registered in the past week has automatically been logged into the wrong table.

**Comment by jclgoodwin** [comment]
i've fixed this now for a few obviously 'New' services but 😡 it might not be possible after all to tell for sure if a service has expired/been cancelled or not. Thought whether it appears in [the Bus_RegisteredOnly_ data](https://data.gov.uk/dataset/9ea90ed8-de54-4274-92c6-272edd518bfb/traffic-commissioners-local-bus-service-registration) would be a reliable test but it looks like it isn't

**Comment by iMarkeh** [comment]
I think this is sorted now isn't it?

**Comment by iMarkeh** [comment]
Sadly, this has to be reopened. A good number of registrations showing up wrongly again.

https://bustimes.org/licences/PH0005857 routes 37, 38, 2700 are all 'variation' but are in the cancelled column.
https://bustimes.org/licences/PH1020951 loads of routes are 'variation' or 'new' but in the cancelled column

**Comment by jclgoodwin** [comment]
sorted now?
