### ISSUE TITLE
Stagecoach Chester Route 1s always confused

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#136]
https://bustimes.org/services/1-chester-blacon-parade

This is 2 completely separate route 1's but for some reason always merged so it's very confusing. There is no interworking or anything, the two routes are standalone. 
1 Chester - Blacon
1 Chester - Liverpool

**Comment by iMarkeh** [comment]
Now happening with Arriva Wales too.

1 Chester - Blacon is being erroneously linked with 1 Chester to Wrexham.

**Comment by jclgoodwin** [comment]
it's difficult because they do have a stop in common – why are there so many route 1s in chester?! – so might impossible to distinguish from actual split registrations. But its probably more feasible for me to fix it somehow than hope they'll renumber their services.

**Comment by iMarkeh** [comment]
> it's difficult because they do have a stop in common – why are there so many route 1s in chester?! – so might be impossible to distinguish from actual split registrations. But it's probably more feasible for me to fix it somehow than hope they'll renumber their services.

There is a lot of route 1's in Chester. It's a bit bonkers haha. They do want to renumber some services but that isn't for a while. Could something be set up as a 'setting' so that if service registration equals x then don't route link?

**Comment by iMarkeh** [comment]
Think you've got this all sorted now.
