### ISSUE TITLE
Need a live tracking symbol on departures

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#140]
On the stops list, if a bus is tracking on that trip (as the system already links buses to trips), it should show a symbol next to the departure so that people are aware that they can track the bus. Similar to how you used to have the thunderbolt to highlight estimated departure instead of scheduled departure

**Comment by jclgoodwin** [comment]
I've thought of this, but haven't worked out how to do it without making it look like the time shown is "live" and not just from the timetable. So first I need to work on calculating delays and predicting actual departure times

**Comment by iMarkeh** [comment]
Hmm. Could the Apple Maps logo style work? Actually showing a map to highlight it?

Also, weren't some of the departures 'live' at one point, not seen them for a while.

**Comment by iMarkeh** [comment]
'Live tracking can now be easier seen as it shows the scheduled and estimated arrival times.
