### ISSUE TITLE
Bus Open Data 'Timing Information Point' issues

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#141]
On the Bus Open Data Transxchange creator, operators are putting in the stop type 'timing point, not timing point, drop off only, pick up only etc'. For some reason, bustimes is picking this up as all stops are timing points. One such example is Link Network. Every single stop shows up (as if it's a timing point) but in reality, only 3 of the stops should be timing points. I've checked the transxchange file and it all looks correct so it seems to be a bustimes issue not liking any files made with the transxchange creator tool from the DFT.

**Comment by jclgoodwin** [comment]
https://www.pti.org.uk/system/files/files/TransXChange%20UK%20PTI%20Profile%20v1.1.pdf (page 65)

> Allowed values are:
> **principalTimingPoint** (note: only this spelling)
> **otherPoint**

so if the DfT tool is using PTP, TIP etc, that's concerning (but not surprising) 

Maybe I should be treating "TIP" differently – maybe I used to but it caused problems with some other operators' data. I can't reemeber

**Comment by iMarkeh** [comment]
Seems to be a DFT issue then, I've reported it to the people who make the transxchange creator tool and hopefully we can get that updated.
![image](https://user-images.githubusercontent.com/88855038/143316337-abc64175-e188-4d5f-b4e4-a9237b0e1e9d.png)

**Comment by jclgoodwin** [comment]
now treating only `principalTimingPoint` (and `PTP`) as a timing point, since a lot of data is using `timeInfoPoint` for non-timing points
