### ISSUE TITLE
Demand proof for livery changes

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#147]
Many livery changes seem to be happening by both trusted and non trusted users. People seem to be making changes based off what insiders are saying or a random sighting of a wrong tracking bus. 

Demanding proof for more changes, especially for things like to the new Stagecoach livery, would reduce wrong edits.

**Comment by iMarkeh** [comment]
#156

**Comment by iMarkeh** [comment]
Sadly, I feel that this needs looking at still as there are a good number of people making edits without proof. The summary notes from some users are laughable demanding that because a bus is being rubbed down, it will be in a certain new livery. If you happen to correct the error, they get very upset, how dare you insult their assumptions. 

Not sure if my old script worked for demanding proof but I feel like if livery is changed, a demand proof box should appear.

**Comment by Clthreeoneeight** [comment]
Require a link in order to post an edit to a livery?
Anyone with an image can go on, say, discord or imgur or whatever and upload an image there and copy the link over.

**Comment by iMarkeh** [comment]
no longer needed. We have rules and a stricter set of moderators.
