### ISSUE TITLE
ITO world disruptions

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#171]
The ITO World disruptions for Merseytravel disruptions show just links, no text. Not very informative.

https://bustimes.org/services/79-liverpool-one-bus-station-halewood-shopping-cen

**Comment by jclgoodwin** [comment]
seems to have improved now? The Transport for the North data no longer exists so ~

**Comment by iMarkeh** [comment]
Does seem to have improved and be on par with the data which was previously being released via Transport for the North
