### ISSUE TITLE
Unhelpful 'and then every x minutes'

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#176]
If it's a clockface timetable, this is ok but 'every 25 minutes' is not helpful at all for passengers. 20 mins or 30 mins is ok but not 25 mins.

![image](https://user-images.githubusercontent.com/88855038/167487375-49e4758c-8d52-4b99-a105-199efc56e7bf.png)

**Comment by jclgoodwin** [comment]
yes it shouldn't be doing that

(https://bustimes.org/services/16-chester-bus-interchange-saltney-sandy-lane-2)
