### ISSUE TITLE
Stagecoach/VIX machine needs cut off

### ISSUE THREAD

**Issue by iMarkeh** [jclgoodwin/bustimes.org#200]
Because of Stagecoach/VIX machines now tracking sometimes without a route, all of the days are combining into one. For example, this bus has been tracking for 10 days so when you go into the map, it can take time to load as it's trying to load so much data. If a cutoff was put at say either midnight or in the middle of the night (as some operators say the new day starts at 2/3am) and any tracking after that time each day then comes under a new day. This then saves issues of endless days worth of data trying to show on a map.

https://bustimes.org/vehicles/sclk-50291

**Comment by jclgoodwin** [comment]
Now starts a new journey each day. I still want to work out how to detect "lengths"/"laps" for journeys that go back and forth (rail replacement etc)
