### ISSUE TITLE
First Greater Glasgow

### ISSUE THREAD

**Issue by callumgourlay** [jclgoodwin/bustimes.org#219]
Hello, 

First Greater Glasgow has had no updates since 4 April. I've tried manually talking to the SPT API endpoint and all seems to be functional. Please let me know where to look if there is anything I can help with!

**Comment by callumgourlay** [comment]
Working again today, but new vehicles operating on services have not shown up today.

**Comment by callumgourlay** [comment]
Vehicles again stopped getting updates on the 19th of April

**Comment by jclgoodwin** [comment]
finally worked out what was wrong, thanks for your patience
