### ISSUE TITLE
Make the map centered on browser's location

### ISSUE THREAD

**Issue by kenguest** [jclgoodwin/bustimes.org#221]
It would be super useful if you could make the map centered on the browser's location and drop the zoom level down a bit - especially on mobile

**Comment by CurtisSouthern** [comment]
The map already has a location button which centers and zooms on your location.
![image](https://user-images.githubusercontent.com/25710026/234936440-26fe2d5d-085e-4da5-b19f-b44d9c390610.png)

**Comment by jclgoodwin** [comment]
for first-time users, the map now uses https://developers.cloudflare.com/support/network/configuring-ip-geolocation/ to roughly centre on Ireland or the UK
