### ISSUE TITLE
Trips not linking up to view expected & actual times

### ISSUE THREAD

**Issue by PlumbBum** [jclgoodwin/bustimes.org#232]
e.g. https://bustimes.org/vehicles/elbg-lx58chd

Usually, the Trip number is clickable which takes you to view a page with expected and actual arrival times along with a pretty map, however these do not appear to be linking up with a trip taking place anymore.

**Comment by PlumbBum** [comment]
My bad, I believe it was the departure time which was clickable. Either or, this doesn't seem to happen anymore for TfL ops.

**Comment by PlumbBum** [comment]
Possibly something to do with this? 12d526c

**Comment by jclgoodwin** [comment]
yes there was a problem with the departure times in the data being hours in the past/future. It looks like this may have been fixed now, so I can reverse the change ...

**Comment by PlumbBum** [comment]
Great work, it's fine now.
