### ISSUE TITLE
map

### ISSUE THREAD

**Issue by luna533** [jclgoodwin/bustimes.org#239]
For some reason whenever you press the map button it auto direct to the following coordinates map#6/54/-2.9 this may be a bug and if it's not a way to set a home area would be useful 🐱

**Comment by iMarkeh** [comment]
Mine reverts to Taunton Train Station for some reason. I checked the map there once and now it seems to think I want to be there all of the time. 

Also, the option for removing stops has gone. Some areas I want to see buses not stops. Stops get in the way of me finding buses.
