### ISSUE TITLE
Duplicate TfL services

### ISSUE THREAD

**Issue by jclgoodwin** [jclgoodwin/bustimes.org#245]
two different causes of duplicates:

- changes of operator (e.g. https://bustimes.org/services/h17-harrow-bus-station-sudbury-wembley-central-2)
- services appearing in BODS, with different operator codes (403: https://bustimes.org/stops/40004410152A)

need to:

- cope with them better (pick one service for avl live tracking)
- ideally not create duplicates in the first place

**Comment by Clthreeoneeight** [comment]
surely the H17 isn't a issue as it's just an operator changing over and then the old operator will eventually remove such route from its data

perhaps have it so it is more clear if a bus route is not running yet, and have the old route with a marker that shows up ~1 week before timetable change and maybe if feasible remove the route 1 day after withdrawal based on the data seen.

could see some issues with certain registered school routes that would need, somehow, an exception

**Comment by jclgoodwin** [comment]
It is an issue. Currently there are two h17s - the current and future version - and no vehicles appear to be tracking on either version, because the code can’t decide which h17 to use
