### ISSUE TITLE
CT4N (Formally Nottingham Community Transport)

### ISSUE THREAD

**Issue by matt13061999** [jclgoodwin/bustimes.org#250]
Good morning, 

I noticed that CT4N doesn't appear to be showing all of its routes like previously on the live map since the additional 18 services have been added the tracking has disappeared im just wondering if its a site issue or a data issue?

Thank you.

**Comment by iMarkeh** [comment]
I know CT4N has no data for any routes/buses which use the older ticket machines, any routes/buses using Ticketer should track though.

**Comment by matt13061999** [comment]
Yeah I know the locallinks never did track but the 18s used to appear because they were all commercial services but since they have added bits to the 18 last Monday the tracking has gone for them.

**Comment by iMarkeh** [comment]
> Yeah I know the locallinks never did track but the 18s used to appear because they were all commercial services but since they have added bits to the 18 last Monday the tracking has gone for them.
Is the 18 still using the Ticketer machines?

**Comment by jclgoodwin** [comment]
It's a data issue, but the missing services (18, 18a, 300, MEDI) *are* tracking in the MyTrip app; I've sent some feedback to CT4N now...

**Comment by matt13061999** [comment]
Thank you josh 🙂

**Comment by matt13061999** [comment]
Hello @jclgoodwin did you ever hear anything back from CT4N regarding this because none of there services apart from 29 tracks anymore but I can see them on there website and the mytrip app?

Thank you for your help.

**Comment by iMarkeh** [comment]
I've been reporting directly to CT4N for months and they aren't bothered about complying with the law. The best way around it now for bustimes would be to use their new Passenger API. This tracks all of their routes too, not just the few operating with Ticketer machines.

https://mytrip.arcticapi.com/network/vehicles?tenant=ctfourn

**Comment by matt13061999** [comment]
@iMarkeh Yeah I agree It looks as though it would serve the same function as there's no joy with CT4N may as well try it.
