### ISSUE TITLE
edit vehicle form

### ISSUE THREAD

**Issue by jclgoodwin** [jclgoodwin/bustimes.org#263]
- [x] use the API to get the list of (vehicle types and) liveries
- [x] add a published=True/False filter to the liveries API
- [x] turn liveries form field into a dropdown box - so the "please wait..." text is easier to notice, and all liveries can be searched through

**Comment by iMarkeh** [comment]
If livery or branding changed, a 'proof link' box appears underneath to try and encourage people to post proof. May help to reduce spam 'I think', 'I heard', 'I assume' edits as people are being prompted for proof.
