### ISSUE TITLE
Allow operator code in search

### ISSUE THREAD

**Issue by Gaelan** [jclgoodwin/bustimes.org#268]
Most of the time when I'm using bustimes.org, I want the timetable for a specific route number (let's say 93, a St Andrews town loop). Currently, the options for this are:

- Type "93" into the search box and scroll through every 93 in the country to find mine.
- Type "93 St Andrews" or "93 Stagecoach East Scotland".

The first is a lot of scrolling; the second is a lot of typing.

What I'd like to be able to do is type "93 SCFI", the operator code for (the relevant part of) Stagecoach East Scotland. This is obviously a niche feature for the kind of person who knows operator codes, but should be fairly easy to implement (I think?) and would be quite convenient for me.

**Comment by jclgoodwin** [comment]
Good idea, thanks! https://bustimes.org/search?q=93+SCFI
