### ISSUE TITLE
d&g 

### ISSUE THREAD

**Issue by luna533** [jclgoodwin/bustimes.org#280]
D&g timetables missing https://bustimes.org/operators/d-g-coach-bus but the are there https://data.bus-data.dft.gov.uk/timetable/dataset/14764/

**Comment by jclgoodwin** [comment]
Alas it says on that page: "**Status** 🔴 Inactive"

**Comment by jclgoodwin** [comment]
using `https://opendata.ticketer.com/uk/D&G_Bus_Ltd/routes_and_timetables/current.zip` while the BODS dataset is inactive
